### ISSUE TITLE
Add async worker queue

### ISSUE THREAD

**Issue by y-ates** [SIWECOS/siwecos-crawler#1]
Add a worker queue, so that several tasks can be requested faster

**Comment by Lednerb** [comment]
Ist dies bereits im `develop`-Branch integriert?

(ich habe `laravel` in `develop` gemerged)

**Comment by Lednerb** [comment]
Ist nicht implementiert.
Bitte __dringend__ nachrüsten.

Ein Post-Request mit `url` und `callbackurls` dauert ca. 5 Sekunden beim Crawl der siwecos.de Seite und liefert `OK` erst, sobald das Crawling abgeschlossen ist.

**Comment by y-ates** [comment]
> Ist dies bereits im develop-Branch integriert?

Ja.

> Ein Post-Request mit url und callbackurls dauert ca. 5 Sekunden beim Crawl der siwecos.de Seite und liefert OK erst, sobald das Crawling abgeschlossen ist.

Wie wurde dies getestet? Die async worker queue ist integriert und funktioniert bei laufender queue wie vorgesehen ("OK" wird sofort zurückgegeben). 

Siehe [dispatch](https://github.com/SIWECOS/siwecos-crawler/blob/develop/app/Http/Controllers/CrawlController.php#L14)

**Comment by y-ates** [comment]
Meine derzeitige Theorie zur Ursache ist die .env.example.
Bei mir läuft es mit folgender .env:

```
APP_NAME=CRAWLER
APP_ENV=local
APP_KEY=base64:C7tfp2hZguzeCJ2JLdiR5+Xj5fn1Ws3ChLeRnUJcIqE=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

BROADCAST_DRIVER=log
CACHE_DRIVER=redis
SESSION_DRIVER=redis
QUEUE_CONNECTION=redis
```

Stammt die .env.example von dir?

**EDIT:** Ich habe meine .env.example hochgeladen

**Comment by Lednerb** [comment]
Lag an der `.env.example`. Fixed in d978b05
