### ISSUE TITLE
Domain als Domain, nicht als URL zurückliefern

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/siwecos-crawler#8]
Momentan liefert der Crawler das folgende Ergebnis:

```
{
    "name": "SIWECOS-CRAWLER",
    "version": "1.2",
    "hasError": false,
    "errorMessage": null,
    "result": {
        "domain": "https://siwecos.de",
        "urls": [
            "https://siwecos.de/cms",
            "https://siwecos.de/app",
            "https://siwecos.de/impressum",
            "https://siwecos.de/news",
            "https://siwecos.de/ueber-das-projekt",
            "https://siwecos.de/support",
            "https://siwecos.de/presse",
            "https://siwecos.de/en/",
            "https://siwecos.de/service-fuer-webhoster",
            "https://siwecos.de/agb"
        ]
    }
}
```

Als `result.domain` soll die Domain `siwecos.de` zurückgeliefert werden, _nicht_ die URL `https://siwecos.de`

**Comment by y-ates** [comment]
Hmm, mit dem Eintrag wollte ich eigentlich das zurückgeben was auch gescannt wurde.
Wenn nur `siwecos.de` zurückgegeben wird kann man nicht erkennen, welches Protokoll denn verwendet wurde.

Ist es wirklich sinnvoller `siwecos.de` zurückzugeben?

Ich meine, ich weiß was du meinst mit **Domain != URL**, evtl. wäre die Umbenennung von `result.domain` besser?

**Comment by Lednerb** [comment]
Dann `startUrl` anstatt `domain` verwenden
